import './globals.css'


import './globals.css'
import AntdConfigProvider from '@/app/components/providers/antdProvider'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdConfigProvider>

          {children}

        </AntdConfigProvider>
      </body>
    </html>
  )
}
